<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:CMR-PUBLICO="CMR-PUBLICO" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="CMR-PUBLICO">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://cmr.funai.gov.br/geoserver/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="lim_quilombolas_aType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="co_sr" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nu_processo" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="no_comunidade" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="no_municipio" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sg_uf" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="dt_publica" nillable="true" type="xsd:date"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="dt_public1" nillable="true" type="xsd:date"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nu_familia" nillable="true" type="xsd:int"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="dt_titulo" nillable="true" type="xsd:date"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nu_area_ha" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="no_responsavel" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="no_esfera" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiSurfacePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="1" name="dt_cadastro" nillable="false" type="xsd:dateTime"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="cd_quilomb" nillable="true" type="xsd:int"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="cd_sipra" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ds_descricao" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="st_titulad" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="dt_decreto" nillable="true" type="xsd:date"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="tp_levanta" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nr_escalao" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ds_fase" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lim_quilombolas_a" substitutionGroup="gml:AbstractFeature" type="CMR-PUBLICO:lim_quilombolas_aType"/>
</xsd:schema>
