from __future__ import annotations

import importlib
import warnings

from agrobr.contracts import BreakingChangePolicy, Column, ColumnType, Contract

CONAB_CUSTO_PRODUCAO_V2 = Contract(
    name="conab.custo_producao",
    version="2.0",
    effective_from="2.0.0",
    primary_key=["cultura", "uf", "safra", "categoria", "item"],
    columns=[
        Column(
            name="cultura",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="safra",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="tecnologia",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="categoria",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="item",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="unidade",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="quantidade_ha",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="unidade/ha",
            stable=True,
            min_value=0,
        ),
        Column(
            name="preco_unitario",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="BRL",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_ha",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="BRL/ha",
            stable=True,
        ),
        Column(
            name="participacao_pct",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="%",
            stable=True,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'safra' always matches pattern YYYY/YY",
        "'uf' is always a valid Brazilian state code",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

DESMATAMENTO_PRODES_V1 = Contract(
    name="desmatamento.prodes",
    version="1.0",
    effective_from="0.10.0",
    primary_key=["ano", "uf", "classe", "bioma"],
    columns=[
        Column(
            name="ano",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=2000,
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="area_km2",
            type=ColumnType.FLOAT,
            nullable=False,
            unit="km2",
            stable=True,
            min_value=0,
        ),
        Column(
            name="satelite",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="sensor",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="bioma",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always >= 2000",
        "'area_km2' is always >= 0",
        "'uf' is always a valid Brazilian state code",
        "'bioma' is always a valid Brazilian biome name",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

DESMATAMENTO_DETER_V1 = Contract(
    name="desmatamento.deter",
    version="1.0",
    effective_from="0.10.0",
    primary_key=["data", "classe", "uf", "municipio", "bioma"],
    columns=[
        Column(
            name="data",
            type=ColumnType.DATE,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="municipio",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="municipio_id",
            type=ColumnType.INTEGER,
            nullable=True,
            stable=True,
        ),
        Column(
            name="area_km2",
            type=ColumnType.FLOAT,
            nullable=False,
            unit="km2",
            stable=True,
            min_value=0,
        ),
        Column(
            name="satelite",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="sensor",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="bioma",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'data' is always a valid date",
        "'area_km2' is always >= 0",
        "'uf' is always a valid Brazilian state code",
        "'bioma' is always 'Amazônia' or 'Cerrado'",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

COMERCIO_BILATERAL_V1 = Contract(
    name="comtrade.comercio",
    version="1.0",
    effective_from="0.11.0",
    primary_key=["periodo", "reporter_iso", "partner_iso", "hs_code", "fluxo_code"],
    columns=[
        Column(
            name="periodo",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="ano",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=1988,
        ),
        Column(
            name="mes",
            type=ColumnType.INTEGER,
            nullable=True,
            stable=True,
            min_value=1,
            max_value=12,
        ),
        Column(
            name="reporter_iso",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="reporter",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="partner_iso",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="partner",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="fluxo_code",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="hs_code",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="produto_desc",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="peso_liquido_kg",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="kg",
            stable=True,
            min_value=0,
        ),
        Column(
            name="volume_ton",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="ton",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_fob_usd",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_cif_usd",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_primario_usd",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
            min_value=0,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always >= 1988",
        "'mes' is between 1 and 12 when present",
        "Numeric values are always >= 0 when present",
        "'fluxo_code' is always 'X' (export) or 'M' (import)",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

TRADE_MIRROR_V1 = Contract(
    name="comtrade.trade_mirror",
    version="1.0",
    effective_from="0.11.0",
    primary_key=["periodo", "hs_code", "reporter_iso", "partner_iso"],
    columns=[
        Column(
            name="periodo",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="ano",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=1988,
        ),
        Column(
            name="mes",
            type=ColumnType.INTEGER,
            nullable=True,
            stable=True,
            min_value=1,
            max_value=12,
        ),
        Column(
            name="hs_code",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="produto_desc",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="reporter_iso",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="partner_iso",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="peso_liquido_kg_reporter",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="kg",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_fob_usd_reporter",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
            min_value=0,
        ),
        Column(
            name="volume_ton_reporter",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="ton",
            stable=True,
            min_value=0,
        ),
        Column(
            name="peso_liquido_kg_partner",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="kg",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_fob_usd_partner",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_cif_usd_partner",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
            min_value=0,
        ),
        Column(
            name="volume_ton_partner",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="ton",
            stable=True,
            min_value=0,
        ),
        Column(
            name="diff_peso_kg",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="kg",
            stable=True,
        ),
        Column(
            name="diff_valor_fob_usd",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="USD",
            stable=True,
        ),
        Column(
            name="ratio_valor",
            type=ColumnType.FLOAT,
            nullable=True,
            stable=True,
        ),
        Column(
            name="ratio_peso",
            type=ColumnType.FLOAT,
            nullable=True,
            stable=True,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always >= 1988",
        "'mes' is between 1 and 12 when present",
        "Mirror compares reporter exports (FOB) vs partner imports (CIF)",
        "'ratio_valor' expected range ~0.85-0.95 for normal trade (FOB/CIF)",
        "'ratio_peso' expected ~1.0 for normal trade",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

ANP_DIESEL_PRECOS_V1 = Contract(
    name="anp_diesel.precos",
    version="1.0",
    effective_from="0.11.0",
    primary_key=["data", "uf", "municipio", "produto"],
    columns=[
        Column(
            name="data",
            type=ColumnType.DATE,
            nullable=False,
            stable=True,
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="municipio",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="produto",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="preco_venda",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="BRL/litro",
            stable=True,
            min_value=0,
        ),
        Column(
            name="preco_compra",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="BRL/litro",
            stable=True,
            min_value=0,
        ),
        Column(
            name="margem",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="BRL/litro",
            stable=True,
        ),
        Column(
            name="n_postos",
            type=ColumnType.INTEGER,
            nullable=True,
            stable=True,
            min_value=0,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'uf' is a valid Brazilian state code when present",
        "'produto' is always 'DIESEL' or 'DIESEL S10'",
        "'preco_venda' and 'preco_compra' are in BRL/litro when present",
        "'margem' equals preco_venda - preco_compra",
        "Data is weekly (date of collection)",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

ANTT_PEDAGIO_FLUXO_V2 = Contract(
    name="antt_pedagio.fluxo",
    version="2.0",
    effective_from="2.0.0",
    primary_key=[
        "data",
        "concessionaria",
        "praca",
        "sentido",
        "n_eixos",
        "tipo_veiculo",
        "categoria_eixo",
    ],
    columns=[
        Column(
            name="data",
            type=ColumnType.DATE,
            nullable=False,
            stable=True,
            description="1o dia do mes",
        ),
        Column(
            name="concessionaria",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="praca",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="sentido",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Crescente/Decrescente",
        ),
        Column(
            name="n_eixos",
            type=ColumnType.INTEGER,
            nullable=True,
            stable=True,
            min_value=2,
            description="Contagem explicita de eixos ou valor numerico da categoria de origem",
        ),
        Column(
            name="tipo_veiculo",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Passeio/Comercial/Moto",
        ),
        Column(
            name="volume",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=0,
            description="Volume de veiculos no mes",
        ),
        Column(
            name="rodovia",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Rodovia (do join com cadastro de pracas)",
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="UF (do join com cadastro de pracas)",
        ),
        Column(
            name="municipio",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Municipio (do join com cadastro de pracas)",
        ),
        Column(
            name="categoria_eixo",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Representacao tarifaria ou de eixos publicada pela origem, sem inferencia",
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'data' is always the 1st day of the month",
        "'n_eixos' preserves numeric source categories or explicit axle counts when available",
        "'categoria_eixo' preserves source category text, including ranges and unknown labels",
        "'volume' is always >= 0",
        "'uf' is a valid Brazilian state code when present",
        "'tipo_veiculo' is always Passeio, Comercial, or Moto when present",
        "Data since 2010 (ANTT open data inception)",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

FERTILIZANTE_V1 = Contract(
    name="anda.fertilizante",
    version="1.0",
    columns=[
        Column(name="ano", type=ColumnType.INTEGER, min_value=2000),
        Column(name="mes", type=ColumnType.INTEGER, min_value=1, max_value=12),
        Column(name="uf", type=ColumnType.STRING, nullable=True),
        Column(name="produto_fertilizante", type=ColumnType.STRING),
        Column(name="volume_ton", type=ColumnType.FLOAT, nullable=True, unit="ton", min_value=0),
    ],
    primary_key=["ano", "mes", "uf", "produto_fertilizante"],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always >= 2000",
        "'mes' is between 1 and 12",
        "Numeric values are always >= 0",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
    effective_from="0.10.0",
)

IMPORTACAO_V1 = Contract(
    name="comexstat.importacao",
    version="1.0",
    columns=[
        Column(name="ano", type=ColumnType.INTEGER, min_value=1997),
        Column(name="mes", type=ColumnType.INTEGER, min_value=1, max_value=12),
        Column(name="produto", type=ColumnType.STRING),
        Column(name="uf", type=ColumnType.STRING, nullable=True),
        Column(name="kg_liquido", type=ColumnType.FLOAT, nullable=True, unit="kg", min_value=0),
        Column(name="valor_fob_usd", type=ColumnType.FLOAT, nullable=True, unit="USD", min_value=0),
    ],
    primary_key=["ano", "mes", "produto", "uf"],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always >= 1997",
        "'mes' is between 1 and 12",
        "Numeric values are always >= 0",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
    effective_from="0.13.0",
)

EXPORTACAO_V1 = Contract(
    name="comexstat.exportacao",
    version="1.0",
    columns=[
        Column(name="ano", type=ColumnType.INTEGER, min_value=1997),
        Column(name="mes", type=ColumnType.INTEGER, min_value=1, max_value=12),
        Column(name="produto", type=ColumnType.STRING),
        Column(name="uf", type=ColumnType.STRING, nullable=True),
        Column(name="kg_liquido", type=ColumnType.FLOAT, nullable=True, unit="kg", min_value=0),
        Column(name="valor_fob_usd", type=ColumnType.FLOAT, nullable=True, unit="USD", min_value=0),
    ],
    primary_key=["ano", "mes", "produto", "uf"],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always >= 1997",
        "'mes' is between 1 and 12",
        "Numeric values are always >= 0",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
    effective_from="0.10.0",
)

CLIMA_V2 = Contract(
    name="datasets.clima",
    version="2.0",
    columns=[
        Column(name="mes", type=ColumnType.DATE),
        Column(name="uf", type=ColumnType.STRING),
        Column(name="precip_acum_mm", type=ColumnType.FLOAT, nullable=True, unit="mm", min_value=0),
        Column(name="temp_media", type=ColumnType.FLOAT, unit="°C"),
        Column(name="temp_max_media", type=ColumnType.FLOAT, unit="°C"),
        Column(name="temp_min_media", type=ColumnType.FLOAT, unit="°C"),
        Column(name="num_estacoes", type=ColumnType.INTEGER, nullable=True, min_value=0),
        Column(
            name="umidade_media",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="%",
            min_value=0,
            max_value=100,
        ),
        Column(
            name="radiacao_media_mj",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="MJ/m²",
            min_value=0,
        ),
        Column(
            name="vento_medio_ms", type=ColumnType.FLOAT, nullable=True, unit="m/s", min_value=0
        ),
        Column(name="fonte", type=ColumnType.STRING),
    ],
    primary_key=["mes", "uf"],
    guarantees=[
        "PK unica por combinacao mes + uf",
        "'uf' sempre uppercase 2 letras",
        "'fonte' sempre 'inmet' ou 'nasa_power'",
        "'num_estacoes' presente apenas quando fonte='inmet'",
        "'umidade_media', 'radiacao_media_mj', 'vento_medio_ms' presentes apenas quando fonte='nasa_power'",
        "Agregacao mensal: 'mes' sempre primeiro dia do mes",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
    effective_from="2.0.0",
)

ZONEAMENTO_AGRICOLA_V1 = Contract(
    name="zarc.zoneamento",
    version="1.0",
    columns=[
        Column(name="cultura", type=ColumnType.STRING),
        Column(name="safra", type=ColumnType.STRING),
        Column(name="geocodigo", type=ColumnType.STRING),
        Column(name="uf", type=ColumnType.STRING),
        Column(name="municipio", type=ColumnType.STRING, nullable=True),
        Column(name="solo_codigo", type=ColumnType.INTEGER),
        Column(name="ciclo_codigo", type=ColumnType.INTEGER),
        Column(name="clima", type=ColumnType.STRING, nullable=True),
        Column(name="manejo", type=ColumnType.STRING, nullable=True),
        Column(name="portaria", type=ColumnType.STRING, nullable=True),
        Column(name="dec1", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec2", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec3", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec4", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec5", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec6", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec7", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec8", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec9", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec10", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec11", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec12", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec13", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec14", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec15", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec16", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec17", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec18", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec19", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec20", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec21", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec22", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec23", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec24", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec25", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec26", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec27", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec28", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec29", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec30", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec31", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec32", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec33", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec34", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec35", type=ColumnType.INTEGER, nullable=True),
        Column(name="dec36", type=ColumnType.INTEGER, nullable=True),
    ],
    primary_key=["cultura", "safra", "geocodigo", "solo_codigo", "ciclo_codigo"],
    guarantees=[
        "Column names never change (additions only)",
        "'geocodigo' is always 7-digit IBGE municipal code",
        "'uf' is always a valid Brazilian state code (2 letters)",
        "'dec1'..'dec36' represent risk per 10-day period (0-5)",
        "'safra' is 'YYYY/YYYY' or 'perene'",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
    effective_from="0.13.0",
)

SICAR_IMOVEIS_V1 = Contract(
    name="sicar.imoveis",
    version="1.0",
    columns=[
        Column(name="cod_imovel", type=ColumnType.STRING),
        Column(name="status", type=ColumnType.STRING),
        Column(name="data_criacao", type=ColumnType.DATETIME, nullable=True),
        Column(name="data_atualizacao", type=ColumnType.DATETIME, nullable=True),
        Column(name="area_ha", type=ColumnType.FLOAT, unit="ha", min_value=0),
        Column(name="condicao", type=ColumnType.STRING, nullable=True),
        Column(name="uf", type=ColumnType.STRING),
        Column(name="municipio", type=ColumnType.STRING),
        Column(name="cod_municipio_ibge", type=ColumnType.INTEGER),
        Column(name="modulos_fiscais", type=ColumnType.FLOAT, min_value=0),
        Column(name="tipo", type=ColumnType.STRING),
    ],
    primary_key=["cod_imovel"],
    guarantees=[
        "Column names never change (additions only)",
        "'cod_imovel' is always non-empty",
        "'status' is always AT, PE, SU, or CA",
        "'tipo' is always IRU, AST, or PCT",
        "'area_ha' is always >= 0",
        "'uf' is always a valid Brazilian state code",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
    effective_from="0.12.0",
)

CLIMA_V1 = Contract(
    name="datasets.clima",
    version="1.0",
    effective_from="0.13.0",
    primary_key=["mes", "uf"],
    columns=[
        Column(name="mes", type=ColumnType.DATE, nullable=False, stable=True),
        Column(name="uf", type=ColumnType.STRING, nullable=False, stable=True),
        Column(
            name="precip_acum_mm",
            type=ColumnType.FLOAT,
            nullable=False,
            stable=True,
            unit="mm",
            min_value=0,
        ),
        Column(name="temp_media", type=ColumnType.FLOAT, nullable=False, stable=True, unit="°C"),
        Column(
            name="temp_max_media", type=ColumnType.FLOAT, nullable=False, stable=True, unit="°C"
        ),
        Column(
            name="temp_min_media", type=ColumnType.FLOAT, nullable=False, stable=True, unit="°C"
        ),
        Column(
            name="num_estacoes", type=ColumnType.INTEGER, nullable=True, stable=True, min_value=0
        ),
        Column(
            name="umidade_media",
            type=ColumnType.FLOAT,
            nullable=True,
            stable=True,
            unit="%",
            min_value=0,
            max_value=100,
        ),
        Column(
            name="radiacao_media_mj",
            type=ColumnType.FLOAT,
            nullable=True,
            stable=True,
            unit="MJ/m²",
            min_value=0,
        ),
        Column(
            name="vento_medio_ms",
            type=ColumnType.FLOAT,
            nullable=True,
            stable=True,
            unit="m/s",
            min_value=0,
        ),
        Column(name="fonte", type=ColumnType.STRING, nullable=False, stable=True),
    ],
    guarantees=[
        "PK unica por combinacao mes + uf",
        "'uf' sempre uppercase 2 letras",
        "'fonte' sempre 'inmet' ou 'nasa_power'",
        "'num_estacoes' presente apenas quando fonte='inmet'",
        "'umidade_media', 'radiacao_media_mj', 'vento_medio_ms' presentes apenas quando fonte='nasa_power'",
        "Agregacao mensal: 'mes' sempre primeiro dia do mes",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

ANTT_PEDAGIO_FLUXO_V1 = Contract(
    name="antt_pedagio.fluxo",
    version="1.0",
    effective_from="0.12.0",
    primary_key=["data", "concessionaria", "praca", "sentido", "n_eixos"],
    columns=[
        Column(
            name="data",
            type=ColumnType.DATE,
            nullable=False,
            stable=True,
            description="1o dia do mes",
        ),
        Column(name="concessionaria", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="praca", type=ColumnType.STRING, nullable=False, stable=True),
        Column(
            name="sentido",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Crescente/Decrescente",
        ),
        Column(
            name="n_eixos",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=2,
            max_value=18,
            description="Numero de eixos do veiculo (2-18)",
        ),
        Column(
            name="tipo_veiculo",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Passeio/Comercial/Moto",
        ),
        Column(
            name="volume",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=0,
            description="Volume de veiculos no mes",
        ),
        Column(
            name="rodovia",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Rodovia (do join com cadastro de pracas)",
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="UF (do join com cadastro de pracas)",
        ),
        Column(
            name="municipio",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
            description="Municipio (do join com cadastro de pracas)",
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'data' is always the 1st day of the month",
        "'n_eixos' is always between 2 and 18",
        "'volume' is always >= 0",
        "'uf' is a valid Brazilian state code when present",
        "'tipo_veiculo' is always Passeio, Comercial, or Moto when present",
        "Data since 2010 (ANTT open data inception)",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

CONAB_CUSTO_PRODUCAO_V1 = Contract(
    name="conab.custo_producao",
    version="1.0",
    effective_from="0.10.0",
    primary_key=["cultura", "uf", "safra", "categoria", "item"],
    columns=[
        Column(name="cultura", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="uf", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="safra", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="tecnologia", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="categoria", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="item", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="unidade", type=ColumnType.STRING, nullable=True, stable=True),
        Column(
            name="quantidade_ha",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="unidade/ha",
            stable=True,
            min_value=0,
        ),
        Column(
            name="preco_unitario",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="BRL",
            stable=True,
            min_value=0,
        ),
        Column(name="valor_ha", type=ColumnType.FLOAT, nullable=True, unit="BRL/ha", stable=True),
        Column(
            name="participacao_pct", type=ColumnType.FLOAT, nullable=True, unit="%", stable=True
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'safra' always matches pattern YYYY/YY",
        "'uf' is always a valid Brazilian state code",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

IBGE_PAM_V1 = Contract(
    name="ibge.pam",
    version="1.0",
    effective_from="0.3.0",
    primary_key=["ano", "produto", "localidade"],
    columns=[
        Column(name="ano", type=ColumnType.INTEGER, nullable=False, stable=True, min_value=1974),
        Column(name="localidade", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="produto", type=ColumnType.STRING, nullable=False, stable=True),
        Column(
            name="area_plantada",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="ha",
            stable=True,
            min_value=0,
        ),
        Column(
            name="area_colhida",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="ha",
            stable=True,
            min_value=0,
        ),
        Column(
            name="producao",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="ton",
            stable=True,
            min_value=0,
        ),
        Column(
            name="rendimento",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="kg/ha",
            stable=True,
            min_value=0,
        ),
        Column(
            name="valor_producao",
            type=ColumnType.FLOAT,
            nullable=True,
            unit="mil_reais",
            stable=True,
            min_value=0,
        ),
        Column(name="fonte", type=ColumnType.STRING, nullable=False, stable=True),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always a valid year (>= 1974)",
        "Numeric values are always >= 0",
        "'fonte' identifies 'ibge_pam' or the 'conab' fallback",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

MAPBIOMAS_COBERTURA_V1 = Contract(
    name="mapbiomas.cobertura",
    version="1.0",
    effective_from="0.10.0",
    primary_key=["bioma", "estado", "classe_id", "ano"],
    columns=[
        Column(
            name="bioma",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="estado",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe_id",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="nivel_0",
            type=ColumnType.STRING,
            nullable=True,
            stable=True,
        ),
        Column(
            name="ano",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=1985,
        ),
        Column(
            name="area_ha",
            type=ColumnType.FLOAT,
            nullable=False,
            unit="ha",
            stable=True,
            min_value=0,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'bioma' is always a valid Brazilian biome name",
        "'estado' is always a valid Brazilian state code (UF)",
        "'ano' is always between 1985 and current year",
        "'area_ha' is always >= 0",
        "'classe_id' maps to MapBiomas LULC legend codes",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

MAPBIOMAS_TRANSICAO_V1 = Contract(
    name="mapbiomas.transicao",
    version="1.0",
    effective_from="0.10.0",
    primary_key=["bioma", "estado", "classe_de_id", "classe_para_id", "periodo"],
    columns=[
        Column(
            name="bioma",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="estado",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe_de_id",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe_de",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe_para_id",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
        ),
        Column(
            name="classe_para",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="periodo",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="area_ha",
            type=ColumnType.FLOAT,
            nullable=False,
            unit="ha",
            stable=True,
            min_value=0,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'bioma' is always a valid Brazilian biome name",
        "'estado' is always a valid Brazilian state code (UF)",
        "'periodo' always matches pattern YYYY-YYYY",
        "'area_ha' is always >= 0",
        "'classe_de_id' and 'classe_para_id' map to MapBiomas LULC legend codes",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

IBGE_CENSO_AGRO_MUNICIPAL_V1 = Contract(
    name="ibge.censo_agro_municipal_1985",
    version="1.0",
    effective_from="0.12.0",
    primary_key=[],
    columns=[
        Column(
            name="ano",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=1985,
            max_value=1985,
        ),
        Column(
            name="uf",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="uf_cod",
            type=ColumnType.INTEGER,
            nullable=False,
            stable=True,
            min_value=11,
            max_value=53,
        ),
        Column(
            name="localidade",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="localidade_cod",
            type=ColumnType.INTEGER,
            nullable=True,
            stable=True,
        ),
        Column(
            name="nivel",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="tema",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="categoria",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="variavel",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="valor",
            type=ColumnType.FLOAT,
            nullable=True,
            stable=True,
            min_value=0,
        ),
        Column(
            name="unidade",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="confianca",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
        Column(
            name="fonte",
            type=ColumnType.STRING,
            nullable=False,
            stable=True,
        ),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'ano' is always 1985",
        "Numeric values are always >= 0",
        "'fonte' is always 'ibge_censo_agro_municipal_1985'",
        "Dados extraídos via OCR de PDFs do IBGE — 22 UFs (excluídos MA/PI/CE/RN)",
        "'confianca' indica qualidade OCR: alta, media ou baixa",
        "'localidade_cod' pode ser None quando OCR não permite match exato",
        "PK vazio: OCR pode gerar labels homônimos (ex: 3 'Santo Antônio' em MG)",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

CREDITO_RURAL_V1_1 = Contract(
    name="bcb.credito_rural",
    version="1.1",
    effective_from="0.10.1",
    primary_key=["safra", "produto", "uf", "finalidade"],
    columns=[
        Column(name="safra", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="produto", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="uf", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="finalidade", type=ColumnType.STRING, nullable=False, stable=True),
        Column(name="agregacao", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="volume", type=ColumnType.FLOAT, nullable=True, stable=True, min_value=0),
        Column(
            name="valor", type=ColumnType.FLOAT, nullable=True, unit="BRL", stable=True, min_value=0
        ),
        Column(name="cd_programa", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="programa", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="cd_fonte_recurso", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="fonte_recurso", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="cd_tipo_seguro", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="tipo_seguro", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="cd_modalidade", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="modalidade", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="cd_atividade", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="atividade", type=ColumnType.STRING, nullable=True, stable=True),
        Column(name="regiao", type=ColumnType.STRING, nullable=True, stable=True),
    ],
    guarantees=[
        "Column names never change (additions only)",
        "'safra' always matches pattern YYYY/YYYY",
        "'uf' is always a valid Brazilian state code when present",
        "Numeric values are always >= 0",
    ],
    breaking_policy=BreakingChangePolicy.MAJOR_VERSION,
)

_CONTRACTS = {
    "MAPBIOMAS_COBERTURA_V1": MAPBIOMAS_COBERTURA_V1,
    "MAPBIOMAS_TRANSICAO_V1": MAPBIOMAS_TRANSICAO_V1,
    "CONAB_CUSTO_PRODUCAO_V2": CONAB_CUSTO_PRODUCAO_V2,
    "DESMATAMENTO_PRODES_V1": DESMATAMENTO_PRODES_V1,
    "DESMATAMENTO_DETER_V1": DESMATAMENTO_DETER_V1,
    "COMERCIO_BILATERAL_V1": COMERCIO_BILATERAL_V1,
    "TRADE_MIRROR_V1": TRADE_MIRROR_V1,
    "ANP_DIESEL_PRECOS_V1": ANP_DIESEL_PRECOS_V1,
    "ANTT_PEDAGIO_FLUXO_V2": ANTT_PEDAGIO_FLUXO_V2,
    "FERTILIZANTE_V1": FERTILIZANTE_V1,
    "IMPORTACAO_V1": IMPORTACAO_V1,
    "EXPORTACAO_V1": EXPORTACAO_V1,
    "CLIMA_V2": CLIMA_V2,
    "ZONEAMENTO_AGRICOLA_V1": ZONEAMENTO_AGRICOLA_V1,
    "SICAR_IMOVEIS_V1": SICAR_IMOVEIS_V1,
    "CLIMA_V1": CLIMA_V1,
    "ANTT_PEDAGIO_FLUXO_V1": ANTT_PEDAGIO_FLUXO_V1,
    "CONAB_CUSTO_PRODUCAO_V1": CONAB_CUSTO_PRODUCAO_V1,
    "IBGE_PAM_V1": IBGE_PAM_V1,
    "IBGE_CENSO_AGRO_MUNICIPAL_V1": IBGE_CENSO_AGRO_MUNICIPAL_V1,
    "CREDITO_RURAL_V1_1": CREDITO_RURAL_V1_1,
}

_ALIASES = {
    "CONAB_SAFRA_V1": ("conab", "CONAB_SAFRA_V2"),
    "IBGE_LSPA_V1": ("ibge", "IBGE_LSPA_V2"),
    "IBGE_CENSO_AGRO_LEGADO_V1": ("ibge", "IBGE_CENSO_AGRO_LEGADO_V2"),
}


def resolve(name: str, *, module: str, names: frozenset[str]) -> Contract:
    contract: Contract
    if name not in names:
        raise AttributeError(f"module {module!r} has no attribute {name!r}")
    if name in _ALIASES:
        target_module, symbol = _ALIASES[name]
        target = importlib.import_module(f"agrobr.contracts.{target_module}")
        contract = getattr(target, symbol)
        description = f"é um alias supersedido de {target_module}.{symbol}"
    else:
        contract = _CONTRACTS[name]
        description = "é um contrato histórico"
    warnings.warn(
        f"{module}.{name} {description}. Use agrobr.contracts.get_contract() "
        "para obter o contrato ativo do dataset.",
        DeprecationWarning,
        stacklevel=3,
    )
    return contract
