<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:geonode="https://geoinfo.dados.embrapa.br" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="https://geoinfo.dados.embrapa.br">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://geoinfo.dados.embrapa.br/geoserver/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="perfis_pronasolos_2020Type">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="1" name="fid" nillable="false" type="xsd:int"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sigla" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="titulo" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ano" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="referencia" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="autor" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nivel_leva" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="codigo_pon" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sigla_bd" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="tipo_ponto" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="responsave" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="data_colet" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="material_o" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="uso_atual" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="observacoe" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="situacao_c" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gcs_latitu" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gcs_longit" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="municipio" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="uf" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="simbolo_ho" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="profundida" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="profundi_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="descricao_" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="calhau" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="cascalho" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="terra_fina" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="areia_gros" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="areia_fina" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="areia_tota" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="silte" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="argila" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="argila_dis" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="grau_flocu" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="relacao_si" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="densidade_" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="densidad_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="porosidade" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="retencao_u" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="retencao_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="agua_dispo" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ph_h2o" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ph_kcl" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="complexo_s" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="complexo_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="complexo_2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="complexo_3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="valor_s" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="aluminio_t" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="hidrogenio" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="valor_t" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="valor_v" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="saturacao_" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="fosforo_as" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="carbono_or" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nitrogenio" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="carbono_ni" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ataque_sul" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ataque_s_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ataque_s_2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ataque_s_3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ataque_s_4" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ataque_s_5" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ki" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="kr" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="al2o3_fe2o" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="cdb_fe" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="equivalent" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="saturaca_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="condutivid" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="agua_pasta" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_e" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_4" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_5" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="sais_sol_6" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="classe_tex" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="grau_consi" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="grau_con_1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="pegajosida" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="plasticida" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:PointPropertyType"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="perfis_pronasolos_2020" substitutionGroup="gml:AbstractFeature" type="geonode:perfis_pronasolos_2020Type"/>
</xsd:schema>
