<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:geonode="https://geoinfo.dados.embrapa.br" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="https://geoinfo.dados.embrapa.br">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://geoinfo.dados.embrapa.br/geoserver/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="brasil_solos_5m_20201104Type">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="1" name="ogc_fid" nillable="false" type="xsd:int"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="simbolos" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="comp1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="comp2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="comp3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="leg_desc" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="area_km2" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ordem1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="subordem1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gdegrupo1" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ordem2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="subordem2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gdegrupo2" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ordem3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="subordem3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gdegrupo3" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="leg_sinot" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="classe_dom" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="geometry" nillable="true" type="gml:MultiSurfacePropertyType"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="brasil_solos_5m_20201104" substitutionGroup="gml:AbstractFeature" type="geonode:brasil_solos_5m_20201104Type"/>
</xsd:schema>
