from __future__ import annotations

from agrobr.constants import URLS, Fonte
from agrobr.utils.geo import LayerConfig

SFB_BASE: str = URLS[Fonte.SFB]["arcgis"]

CATEGORIAS_CNFP: frozenset[str] = frozenset(
    {
        "APA",
        "ARIE",
        "ESEC",
        "FLONA",
        "FLOR PUB DEST",
        "FLOR PUB DEST / APA",
        "FLOTA",
        "GLEBA ARRECADADA",
        "MONA",
        "OUTROS",
        "OUTROS / APA",
        "OUTROS / PARES",
        "OUTROS / REBIO",
        "OUTROS / RVS",
        "PA",
        "PA.",
        "PA / APA",
        "PA / ARIE",
        "PAC",
        "PAC / APA",
        "PAC / FLONA",
        "PAE",
        "PAE / APA",
        "PAE / ARIE",
        "PAE / FLONA",
        "PAE / FLOTA",
        "PAE / PARES",
        "PAE / PARNA",
        "PAE / RDS",
        "PAE / RESEX",
        "PA / ESEC",
        "PAE / TRQ",
        "PAF",
        "PA / FLONA",
        "PA / FLOTA",
        "PAF / RESEX",
        "PA / MONA",
        "PA / OUTROS",
        "PA / OUTROS / APA",
        "PA / PARES",
        "PA / PARMU",
        "PA / PARNA",
        "PAQ",
        "PAQ / FLOTA",
        "PAQ / REBIO",
        "PAQ / TRQ",
        "PA / RDS",
        "PA / REBIO",
        "PARES",
        "PA / RESEX",
        "PARMU",
        "PARNA",
        "PA / RVS",
        "PA / TRQ",
        "PA / TRQ / APA",
        "PA / TRQ / RVS",
        "PC",
        "PCA",
        "PCA / APA",
        "PDS",
        "PDS / APA",
        "PDS / ESEC",
        "PDS / FLONA",
        "PDS / FLOTA",
        "PDS / PARES",
        "PDS / PARNA",
        "PDS / RDS",
        "PDS / RESEX",
        "PE",
        "PEC",
        "PIC",
        "PIC / APA",
        "PIC / PARMU",
        "RDS",
        "REBIO",
        "REFAU",
        "RESEX",
        "RVS",
        "TI",
        "TI / APA",
        "TI / ARIE",
        "TI / ESEC",
        "TI / FLONA",
        "TI / FLOTA",
        "TI / PA",
        "TI / PA / APA",
        "TI / PA / ARIE",
        "TI / PAE",
        "TI / PA / REBIO",
        "TI / PARES",
        "TI / PA / RESEX",
        "TI / PARMU",
        "TI / PARNA",
        "TI / PDS",
        "TI / PRB",
        "TI / PRB / APA",
        "TI / RDS",
        "TI / REBIO",
        "TI / RESEX",
        "TI / RVS",
        "TI / TRQ",
        "TI / USO MILITAR",
        "TI / USO MILITAR / ESEC",
        "TI / USO MILITAR / FLONA",
        "TI / USO MILITAR / PDS",
        "TRQ",
        "TRQ / APA",
        "TRQ / FLONA",
        "TRQ / FLOTA",
        "TRQ / MONA",
        "TRQ / PARES",
        "TRQ / PARNA",
        "TRQ / REBIO",
        "TRQ / RESEX",
        "TRQ / RVS",
        "USO MILITAR",
        "USO MILITAR / APA",
        "USO MILITAR / ESEC",
        "USO MILITAR / FLONA",
        "USO MILITAR / FLOTA",
        "USO MILITAR / MONA",
        "USO MILITAR / PA",
        "USO MILITAR / PAE",
        "USO MILITAR / PARES",
        "USO MILITAR / PARMU",
        "USO MILITAR / PARNA",
        "USO MILITAR / PDS",
        "USO MILITAR / REBIO",
        "USO MILITAR / RESEX",
        "USO MILITAR / RVS",
        "USO MILITAR / TRQ",
        "USO MILITAR / TRQ / APA",
    }
)

LAYERS: dict[str, LayerConfig] = {
    "cnfp": {
        "service_path": "Hosted/CNFP_v19_03_retificado_17072025/FeatureServer/9",
        "max_record_count": 2000,
        "oid_field": "fid",
        "fields": "fid,nome,uf,bioma,categoria,tipo,governo,classe,area_ha,anocriacao,municipio",
        "rename_map": {
            "anocriacao": "ano_criacao",
        },
        "colunas_saida": [
            "fid",
            "nome",
            "uf",
            "bioma",
            "categoria",
            "tipo",
            "governo",
            "classe",
            "area_ha",
            "ano_criacao",
            "municipio",
        ],
        "required_cols": {"nome", "uf"},
    },
    "concessoes": {
        "service_path": "Hosted/unidades_concessoes_florestais/FeatureServer/0",
        "max_record_count": 2000,
        "oid_field": "fid",
        "fields": "fid,nome_uc,uf,bioma,hectares,criacao,grupo,cat_nome",
        "rename_map": {
            "nome_uc": "nome",
            "hectares": "area_ha",
            "criacao": "ano_criacao",
            "cat_nome": "categoria",
        },
        "colunas_saida": [
            "fid",
            "nome",
            "uf",
            "bioma",
            "area_ha",
            "ano_criacao",
            "grupo",
            "categoria",
        ],
        "required_cols": {"nome_uc"},
    },
    "ifn_conglomerados": {
        "service_path": "DadosAbertos-IFN/Conglomerado/FeatureServer/0",
        "max_record_count": 2000,
        "fields": "co_pontos_lote,co_lote,no_lote,no_conglomerado,no_uf,no_municipio,no_bioma",
        "rename_map": {
            "co_pontos_lote": "id",
            "co_lote": "codigo_lote",
            "no_lote": "lote",
            "no_conglomerado": "conglomerado",
            "no_uf": "uf",
            "no_municipio": "municipio",
            "no_bioma": "bioma",
        },
        "colunas_saida": [
            "id",
            "codigo_lote",
            "lote",
            "conglomerado",
            "uf",
            "municipio",
            "bioma",
        ],
        "required_cols": {"no_uf"},
    },
}
